# Generated by Django 4.2.19 on 2025-03-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="must_change_password",
            field=models.BooleanField(
                default=True,
                help_text="Detyron përdoruesin të ndryshojë fjalëkalimin në hyrjen e parë.",
            ),
        ),
    ]
