# Generated by Django 4.2.19 on 2025-03-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        choices=[
                            ("Salla 1", "Salla 1"),
                            ("Salla 2", "Salla 2"),
                            ("Salla 3", "Salla 3"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
            ],
        ),
    ]
