# Generated by Django 4.2.19 on 2025-03-09 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="year",
            field=models.IntegerField(default=2025, verbose_name="Viti"),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aprovuar nga",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Data e Krijimit"
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Punonjësi",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateField(verbose_name="Data e Mbarimit"),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("Annual", "Leje Vjetore"),
                    ("Sick", "Leje Mjekësore"),
                    ("Other", "Tjetër"),
                ],
                max_length=50,
                verbose_name="Lloji i Lejes",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="start_date",
            field=models.DateField(verbose_name="Data e Fillimit"),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Në Pritje"),
                    ("Approved", "Aprovuar"),
                    ("Rejected", "Refuzuar"),
                ],
                default="Pending",
                max_length=20,
                verbose_name="Statusi",
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Data e Përditësimit"
            ),
        ),
    ]
