# Generated by Django 4.2.19 on 2025-03-09 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leaves", "0002_leaverequest_year_alter_leaverequest_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Punonjësi",
            ),
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Viti")),
                (
                    "total_leave_days",
                    models.IntegerField(default=20, verbose_name="Ditë Leje Totale"),
                ),
                (
                    "used_leave_days",
                    models.IntegerField(
                        default=0, verbose_name="Ditë Leje të Përdorura"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Punonjësi",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "year")},
            },
        ),
    ]
