# Generated by Django 4.2.19 on 2025-03-09 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0003_alter_leaverequest_employee_leavebalance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Data e Krijimit",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=1, verbose_name="Data e Përditësimit"
            ),
            preserve_default=False,
        ),
    ]
