# Generated by Django 4.2.19 on 2025-03-09 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0004_alter_leaverequest_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data e Krijimit"
            ),
        ),
    ]
