# Generated by Django 4.2.19 on 2025-03-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0005_alter_leaverequest_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data e Krijimit"
            ),
        ),
    ]
