# Generated by Django 4.2.19 on 2025-03-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaves", "0006_alter_leaverequest_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavebalance",
            name="custom_leave_days",
            field=models.IntegerField(
                default=22, verbose_name="Ditë Leje të Përcaktuara nga Admini"
            ),
        ),
        migrations.AlterField(
            model_name="leavebalance",
            name="total_leave_days",
            field=models.IntegerField(default=22, verbose_name="Ditë Leje Totale"),
        ),
    ]
